/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/littleComponents/Avatar/Avatar.vue')['default']
    BottomLoading: typeof import('./src/components/littleComponents/Loading/bottomLoading.vue')['default']
    CmtyCard: typeof import('./src/components/Cards/CmtyCard/index.vue')['default']
    CmtyCreator: typeof import('./src/components/CmtyCreator/index.vue')['default']
    CmtySelector: typeof import('./src/components/Editor/CmtySelector.vue')['default']
    CommentCard: typeof import('./src/components/Cards/CommentCard/CommentCard.vue')['default']
    CommentEditor: typeof import('./src/components/Editor/CommentEditor/index.vue')['default']
    DarkMask: typeof import('./src/components/littleComponents/Mask/darkMask.vue')['default']
    Editor: typeof import('./src/components/Editor/Editor.vue')['default']
    EditorShowingBtn: typeof import('./src/components/littleComponents/EditorShowingBtn/EditorShowingBtn.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    FavoriteBtn: typeof import('./src/components/littleComponents/FavoriteBtn/FavoriteBtn.vue')['default']
    FollowBtn: typeof import('./src/components/littleComponents/FollowBtn/FollowBtn.vue')['default']
    Head: typeof import('./src/components/Head/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Images: typeof import('./src/components/Images/Images.vue')['default']
    ImgDisplayer: typeof import('./src/components/Images/ImgDisplayer.vue')['default']
    ImgSelector: typeof import('./src/components/Editor/ImgSelector.vue')['default']
    JoinBtn: typeof import('./src/components/littleComponents/JoinBtn/JoinBtn.vue')['default']
    LeftAvatarPanel: typeof import('./src/components/littleComponents/Avatar/LeftAvatarPanel.vue')['default']
    LoadingSpinner: typeof import('./src/components/littleComponents/Loading/loadingSpinner.vue')['default']
    LoginAndRegister: typeof import('./src/components/LoginAndRegister/index.vue')['default']
    MainFloor: typeof import('./src/components/Floor/MainFloor.vue')['default']
    MainPage: typeof import('./src/components/MainPage/index.vue')['default']
    Mask: typeof import('./src/components/littleComponents/Mask.vue')['default']
    MoreNav: typeof import('./src/components/MoreNav/index.vue')['default']
    Nav: typeof import('./src/components/MainPage/Nav/Nav.vue')['default']
    NotiCard: typeof import('./src/components/Cards/NotiCard/index.vue')['default']
    PostCard: typeof import('./src/components/Cards/PostCard/index.vue')['default']
    PostEditor: typeof import('./src/components/Editor/PostEditor/PostEditor.vue')['default']
    PostMenu: typeof import('./src/components/PostMenu/index.vue')['default']
    Recyle: typeof import('./src/components/Tools/recyle.vue')['default']
    Reply: typeof import('./src/components/Floor/Reply.vue')['default']
    ReplyEditor: typeof import('./src/components/Editor/ReplyEditor/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBtn: typeof import('./src/components/littleComponents/searchBtn/SearchBtn.vue')['default']
    SubFloor: typeof import('./src/components/Floor/SubFloor.vue')['default']
    Tab: typeof import('./src/components/Tab/index.vue')['default']
    Tools: typeof import('./src/components/Tools/index.vue')['default']
    Top: typeof import('./src/components/Top/Top.vue')['default']
    UserCard: typeof import('./src/components/UserCard/index.vue')['default']
    YyReturn: typeof import('./src/components/littleComponents/yy-button/yy-return.vue')['default']
  }
}
